# Path to the rule file
# Extension can be toml or lua.
RuleFile = "rules.toml"

LogDirectory = "Logs"
CacheDirectory = "Cache"

WindowTitle = "Asset Cooker for Arkose"

[[Repo]]
Name = "Assets"
Path = '../../assets/assets/'

[[Repo]]
Name = "Imported"
Path = '../../assets/imported/'

[[Repo]]
Name = "Tools"
Path = '.'
