[[Rule]]
Name = "Import glTF model"
InputFilters = [ 
    { Repo = "Assets", PathPattern = "*.gltf" },
    { Repo = "Assets", PathPattern = "*.glb" },
]
CommandLine = '{ Repo:Tools }GltfImportTool.exe "{ Repo:Assets }{ Path }" "{ Repo:Imported }{ Dir }"'
DepFile = { Path = '{ Repo:Imported }{ Dir }dependencies.dep', Format = 'AssetCooker' }

#[[Rule]]
#Name = "Convert IES profile to LUT"
#InputFilters = [ 
#    { Repo = "Assets", PathPattern = "*.ies" },
#]
#CommandLine = '{ Repo:Tools }IESConvertTool.exe "{ Repo:Assets }{ Path }" "{ Repo:Imported }{ Dir }{ File }{ Ext }.dds"'
#OutputPaths = [ '{ Repo:Imported }{ Dir }{ File }{ Ext }.dds' ]

[[Rule]]
Name = "Copy IES profiles (TODO: Use the converted DDS LUTs!)"
InputFilters = [
    { Repo = "Assets", PathPattern = "*.ies" },
]
CommandLine = '{ Repo:Tools }CopyFileTool.exe "{ Repo:Assets }{ Path }" "{ Repo:Imported }{ Path }"'
OutputPaths = [ '{ Repo:Imported }{ Path }' ]

[[Rule]]
Name = "Bake Arkose asset"
InputFilters = [ 
    { Repo = "Assets", PathPattern = "*.arkanim" },
    { Repo = "Assets", PathPattern = "*.arklvl" },
    { Repo = "Assets", PathPattern = "*.arkmat" },
    { Repo = "Assets", PathPattern = "*.arkmsh" },
    { Repo = "Assets", PathPattern = "*.arkskel" },
]
CommandLine = '{ Repo:Tools }ArkAssetBakeTool.exe "{ Repo:Assets }{ Path }" "{ Repo:Imported }{ Path }"'
OutputPaths = [ '{ Repo:Imported }{ Path }' ]

[[Rule]]
Name = "Bake image assets"
InputFilters = [ 
    { Repo = "Assets", PathPattern = "icons/*.png" },
    { Repo = "Assets", PathPattern = "default/*.png" },
    { Repo = "Assets", PathPattern = "blue-noise/*.png" },
]
CommandLine = '{ Repo:Tools }ImgAssetBakeTool.exe "{ Repo:Assets }{ Path }" "{ Repo:Imported }{ Dir }{ File }.dds"'
OutputPaths = [ '{ Repo:Imported }{ Dir }{ File }.dds' ]
