[[Rule]]
Name = "Import glTF model"
InputFilters = [ 
    { Repo = "Assets", PathPattern = "*.gltf" },
    { Repo = "Assets", PathPattern = "*.glb" },
]
CommandLine = '{ Repo:Tools }GltfImportTool.exe "{ Repo:Assets }{ Path }" "{ Repo:Imported }{ Dir }"'
DepFile = { Path = '{ Repo:Imported }{ Dir }dependencies.dep', Format = 'AssetCooker' }
