[[Rule]]
Name = "Import glTF"
InputFilters = [ 
    { Repo = "Assets", PathPattern = "*.gltf" },
    { Repo = "Assets", PathPattern = "*.glb" },
]
CommandLine = '{ Repo:Tools }GltfImportTool.exe "{ Repo:Assets }{ Path }" "{ Repo:Imported }{ Dir }" "{ Repo:Temp }{ Dir }"'
DepFile = { Path = '{ Repo:Temp }{ Path }.dep', Format = 'AssetCooker' }
Priority = 0

[[Rule]]
Name = "Import USD"
InputFilters = [ 
    { Repo = "Assets", PathPattern = "*.usd" },
    { Repo = "Assets", PathPattern = "*.usda" },
    { Repo = "Assets", PathPattern = "*.usdc" },
]
CommandLine = '{ Repo:Tools }usd/UsdImportTool.exe "{ Repo:Assets }{ Path }" "{ Repo:Imported }{ Dir }" "{ Repo:Temp }{ Dir }"'
DepFile = { Path = '{ Repo:Temp }{ Path }.dep', Format = 'AssetCooker' }
Priority = 0

[[Rule]]
Name = "Bake imgspec"
InputFilters = [ 
    { Repo = "Temp", PathPattern = "*.imgspec" },
]
CommandLine = '{ Repo:Tools }ImgAssetBakeTool.exe "{ Repo:Temp }{ Path }"'
DepFile = { Path = '{ Repo:Temp }{ Path }.dep', Format = 'AssetCooker' }
Priority = 1 # ensure producers of imgspec files run first (the asset importers)

#[[Rule]]
#Name = "Convert IES profile to LUT"
#InputFilters = [ 
#    { Repo = "Assets", PathPattern = "*.ies" },
#]
#CommandLine = '{ Repo:Tools }IESConvertTool.exe "{ Repo:Assets }{ Path }" "{ Repo:Imported }{ Dir }{ File }{ Ext }.dds"'
#OutputPaths = [ '{ Repo:Imported }{ Dir }{ File }{ Ext }.dds' ]
#Priority = 2

[[Rule]]
Name = "Copy IES" # TODO: Use the converted DDS LUTs!
InputFilters = [
    { Repo = "Assets", PathPattern = "*.ies" },
]
CommandType = "CopyFile"
OutputPaths = [ '{ Repo:Imported }{ Path }' ]
Priority = 2

[[Rule]]
Name = "Bake asset"
InputFilters = [ 
    { Repo = "Assets", PathPattern = "*.arkanim" },
    { Repo = "Assets", PathPattern = "*.arklvl" },
    { Repo = "Assets", PathPattern = "*.arkmat" },
    { Repo = "Assets", PathPattern = "*.arkmsh" },
    { Repo = "Assets", PathPattern = "*.arkskel" },
]
CommandLine = '{ Repo:Tools }ArkAssetBakeTool.exe "{ Repo:Assets }{ Path }" "{ Repo:Imported }{ Path }"'
OutputPaths = [ '{ Repo:Imported }{ Path }' ]
Priority = 2

[[Rule]]
Name = "Bake image"
InputFilters = [ 
    { Repo = "Assets", PathPattern = "*.hdr" },
    { Repo = "Assets", PathPattern = "engine/icons/*.png" },
    { Repo = "Assets", PathPattern = "engine/default/*.png" },
    { Repo = "Assets", PathPattern = "engine/blue-noise/*.png" },
]
CommandLine = '{ Repo:Tools }ImgAssetBakeTool.exe "{ Repo:Assets }{ Path }" "{ Repo:Imported }{ Dir }{ File }.dds"'
OutputPaths = [ '{ Repo:Imported }{ Dir }{ File }.dds' ]
Priority = 2

[[Rule]]
Name = "Copy .cube LUT"
InputFilters = [ 
   { Repo = "Assets", PathPattern = "*.cube" },
]
CommandType = "CopyFile"
OutputPaths = [ '{ Repo:Imported }{ Path }' ]
Priority = 2
