#ifndef TONEMAP_DATA_H
#define TONEMAP_DATA_H

#define TONEMAP_METHOD_CLAMP    1
#define TONEMAP_METHOD_REINHARD 2
#define TONEMAP_METHOD_ACES     3
#define TONEMAP_METHOD_AGX      4

#endif // TONEMAP_DATA_H
