#ifndef PROBE_DEBUG_H
#define PROBE_DEBUG_H

#define PROBE_DEBUG_VISUALIZE_IRRADIANCE 0
#define PROBE_DEBUG_VISUALIZE_DISTANCE   1
#define PROBE_DEBUG_VISUALIZE_DISTANCE2  2

// What should be shown by DiffuseGIProbeDebug?
#define PROBE_DEBUG_VIZ PROBE_DEBUG_VISUALIZE_IRRADIANCE

#endif // PROBE_DEBUG_H
